#!/usr/bin/env python3

import ast
import sys


def main():
    output = sys.stdin.read()
    end_output = "() : Void\n"
    if output.endswith(end_output):
        output = output[: -len(end_output)]

    for line in output.splitlines():
        if line.startswith('"'):
            print(ast.literal_eval(line))
        else:
            print(line)


if __name__ == "__main__":
    main()
